import { useEffect, useState } from 'react'
import { getData, getFiles } from '../services/api'
import { dateFromFileName, formatBytes, formatDate, formatUptime } from '../utils/format'
import MetricCard from '../components/MetricCard'
import StatusBadge from '../components/StatusBadge'
import LoadingState from '../components/LoadingState'
import ErrorState from '../components/ErrorState'

export default function DashboardPage({ status }) {
  const [files, setFiles] = useState([]); const [preview, setPreview] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const result = await getFiles(); setFiles(result); const date = dateFromFileName(result[0]?.name); if (date) { try { const data = await getData(date); setPreview([...data.readings].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp)).slice(0, 5)) } catch { setPreview([]) } } } catch (e) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const totalSize = files.reduce((sum, file) => sum + file.sizeBytes, 0)
  return <div className="page-stack">{!status && <ErrorState message="Backend unavailable: unable to load pipeline status." />}<div className="card-grid"> <MetricCard label="Pipeline status" value={<StatusBadge active={status?.isRunning} activeLabel="Running" inactiveLabel="Stopped" />} detail={formatDate(status?.startedAt)} /><MetricCard label="PI Web API" value={<StatusBadge active={status?.piApiConnected} />} /><MetricCard label="MinIO" value={<StatusBadge active={status?.minioConnected} />} /><MetricCard label="Current file" value={status?.currentFile?.name || 'No active file'} detail={formatBytes(status?.currentFile?.sizeBytes)} /><MetricCard label="Last collection" value={formatDate(status?.lastCollectionAt)} /><MetricCard label="Last upload" value={formatDate(status?.lastUploadAt)} /><MetricCard label="Total files" value={files.length} detail="Objects in MinIO" /><MetricCard label="Total storage" value={formatBytes(totalSize)} detail={`Latest: ${files[0]?.name || 'Not available'}`} /><MetricCard label="Uptime" value={status?.isRunning ? formatUptime(status.startedAt) : 'Not running'} detail={status?.lastUploadedFile ? `Last uploaded: ${status.lastUploadedFile}` : 'No uploaded file yet'} /></div><section className="panel"><div className="panel-heading"><div><h2>Latest data</h2><p>Five most recent records from the latest available CSV date.</p></div><button className="secondary-button" onClick={load}>Refresh files</button></div>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : preview.length === 0 ? <div className="empty-state">No data available.</div> : <div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Element</th><th>Atelier</th><th>Pressure</th><th>Process temp</th></tr></thead><tbody>{preview.map((row, index) => <tr key={`${row.element}-${row.timestamp}-${index}`}><td>{formatDate(row.timestamp)}</td><td>{row.element}</td><td>{row.atelier}</td><td>{row.pressure}</td><td>{row.processTemp}</td></tr>)}</tbody></table></div>}</section></div>
}
